export const journalTechBloggerSources = [
    { name: '阮一峰的网络日志', homepage: 'https://www.ruanyifeng.com/blog/weekly/' },
    { name: '奇舞周刊', homepage: 'https://weekly.75.team/' },
    { name: 'HelloGitHub', homepage: 'https://hellogithub.com/' },
    { name: '好工具周刊 BestXTools', homepage: 'https://bestxtools.zhubai.love/' },
    { name: 'Easy Indie', homepage: 'https://www.ezindie.com/' },
    { name: 'DecoHack周刊', homepage: 'https://decohack.zhubai.love/' },
    { name: '老胡的周刊', homepage: 'https://weekly.howie6879.com/' },
    { name: '酷壳 CoolShell（已故）', homepage: 'https://coolshell.cn/' },
    { name: '美团技术团队', homepage: 'https://tech.meituan.com/' },
    { name: '张鑫旭-鑫空间-鑫生活', homepage: 'https://www.zhangxinxu.com/wordpress/' },
    { name: '鸟窝', homepage: 'https://colobu.com/' },
    { name: '峰华前端工程师', homepage: 'https://zxuqian.cn/' },
    { name: '运维咖啡吧', homepage: 'https://blog.ops-coffee.cn/' },
    { name: '李文周的博客', homepage: 'https://www.liwenzhou.com/' },
    { name: '无忌', homepage: 'https://jincheng9.github.io/' },
    { name: 'Tony Bai', homepage: 'https://tonybai.com/' },
    { name: '午夜咖啡', homepage: 'https://jolestar.com/' },
    { name: '深度学习前沿笔记', homepage: 'https://www.zhihu.com/column/c_188941548' },
    { name: 'RandomGenerator', homepage: 'https://www.zhihu.com/column/zijie0' },
    { name: 'iCSS前端趣闻', homepage: 'https://juejin.cn/user/2330620350437678/posts?sort=newest' },
    { name: '字节跳动技术团队', homepage: 'https://juejin.cn/user/1838039172387262/posts?sort=newest' },
    { name: 'SegmentFault Weekly', homepage: 'https://segmentfault.com/weekly' },
    { name: '云风的BLOG', homepage: 'https://blog.codingnow.com/' },
    { name: 'Phodal Huang', homepage: 'https://www.phodal.com/' },
    { name: 'Python猫', homepage: 'https://pythoncat.top/' },
    { name: 'Next.js Blog', homepage: 'https://nextjs.org/blog' },
    { name: "Sukka's Blog", homepage: 'https://blog.skk.moe/' },
    { name: 'OpenAI Blog', homepage: 'https://openai.com/blog/' },
    { name: 'Vue.js Blog', homepage: 'https://blog.vuejs.org/' },
    { name: 'Go Blog', homepage: 'https://go.dev/blog/' },
    { name: '安富莱嵌入式周报', homepage: 'https://www.armbbs.cn/forum.php?mod=forumdisplay&fid=12&filter=author&orderby=dateline&typeid=104' },
    { name: 'Java News', homepage: 'https://dev.java/news/' },
    { name: '.NET Blog', homepage: 'https://devblogs.microsoft.com/dotnet/' },
    { name: 'C++ Team Blog', homepage: 'https://devblogs.microsoft.com/cppblog/' },
    { name: '.NET中文官方博客', homepage: 'https://devblogs.microsoft.com/dotnet-ch/' },
    { name: 'Rust Blog', homepage: 'https://blog.rust-lang.org/' },
    { name: "Eli Bendersky's website", homepage: 'https://eli.thegreenplace.net/' },
    { name: 'Apple Developer News', homepage: 'https://developer.apple.com/cn/news/' },
    { name: 'PolarDB 数据库内核月报', homepage: 'http://mysql.taobao.org/monthly/' },
    { name: '得物技术', homepage: 'https://juejin.cn/user/2392954206960247/posts?sort=newest' },
    { name: '网易云音乐技术团队', homepage: 'https://juejin.cn/user/4265760847567016/posts?sort=newest' },
];
